
all: utility_client

utility_client:
	g++ -g -std=c++11 -I../../dependencies/websocketpp/ -I../../dependencies/boost_1_72_0/ utility_client.cpp -o utility_client \
    -lpthread 


clean:
	rm -rf utility_client
